name: keyline
description: A musical visualization tool for tonalities and keys.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.9

dependencies:
  flutter:
    sdk: flutter
  music_notes: ^0.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.1.0

flutter:
  uses-material-design: true
