name: keyline
description: A musical visualization tool for tonalities and keys.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.9

dependencies:
  flutter:
    sdk: flutter
  music_notes:
    git:
      url: https://github.com/albertms10/music_notes.git
      ref: main
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.1.0

flutter:
  uses-material-design: true
